name: contextsdemo

on: push
jobs:
  echo-contextdata:
    runs-on: ubuntu-latest
    steps:
      - name: Display contxt information
        run: |
          echo "Event github.event_name: ${{github.event_name}}
          echo "actor: ${{github.actor}}"
          echo "env: ${{github.env}}"
          echo "Path: ${{github.path}}"
