name: contextsdemo

on: push
jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps:
      - name: Display contxt information
        run: |
          echo "Event Name: ${{github.event_name}}"
          echo "actor: ${{github.actor}}"
          echo "env: ${{github.env}}"
          echo "Path: ${{github.path}}"

      - name: Retreive Variables
        run: |
          echo "Variable value: ${{vars.REPOSITORY_VAR}}"
    

